# Site settings
title:          wyy18feb's blog
description:    "Welcome to my blog!"
baseurl:        "/"
url:            "https://wyy18feb.github.io"

# Google Analytics
google_analytics:

# Author
author:
  name:         wyy18feb
  url:          https://wyy18feb.github.io
  email:        wyy18feb@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
